using PartnerForecast.Website.Application.Features.AuditLogs.Models;
using PartnerForecast.Website.Application.Features.Users.Models;
using System.Text.Json;

namespace PartnerForecast.Website.Application;

internal static class SharedExtensions
{

    public static IEnumerable<User> ToUsers(this IEnumerable<LdapUser> ldapUsers, string domain)
    {
        List<User> users = new List<User>();
        users.AddRange(
            ldapUsers.Where(u =>
                u is not null &&
                u.EmployeeId > 0 &&
                u.IsActive &&
                string.Equals(u.Domain, domain, StringComparison.OrdinalIgnoreCase))
            .OrderBy(u => u.EmployeeName)
            .Select(u => new User(
                EmployeeNumber:u.EmployeeId,
                EmployeeName: u.EmployeeName,
                EmailAddress: u.EmailAddress,
                Title: u.Title,
                IsAdmin: false,
                IsInactive: !u.IsActive,            
                EmployeeDomain: domain,
                IsEQRUser: false))
            );
        return users;
    }       
    

    public static AuditLogTable ConvertToAuditLogTable(this AuditLogRecord log)
    {

        return new AuditLogTable
            (
                0, //Id to be automatilly generated by the database
                log.ClientHoursId,
                log.LogCategory,
                log.ChangedByEmployeeNumber,
                log.ChangeDescription,
                JsonSerializer.Serialize(log.Changes),
                DateTime.Now,
                log.ChangedByEmployeeName,
                log.ChangedByEmployeeDomain
            );
    }





}
